web_s10185214/web_s10185214/Models/Rental.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace web_s10185214.Models
{
    public class RentalDiscount
    {
        public string Description { get; set; }
        public double DiscountPercent { get; set; }
        public bool Selected { get; set; }
    }
    public class Rental
    {
        [Display(Name = "Loan Date")]
        [DataType(DataType.Date)]
        
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime LoanDate { get; set; }


        [Display(Name = "Date Of Birth")]
        [DataType(DataType.Date)]

        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DOB { get; set; }

        public bool BirthMonth { get; set; }


        [Display(Name = "Number of Books")]
        public int NumBooks { get; set; }

        [Display(Name = "Number of Days")]
        public int NumDays { get; set; }


        [Display(Name = "Rental Rate (SGD)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public double RentalRate { get; set; }
        [Display(Name = "Due Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}")]
        public DateTime DueDate { get; set; }
        [Display(Name = "Rental Fee (SGD)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public double RentalFee { get; set; }
        [Display(Name = "Discount Given (%)")]
        [DisplayFormat(DataFormatString = "{0:#0.0}")]
        public double DiscountPercent { get; set; }
        [Display(Name = "Discount Given (%)")]
        public List<RentalDiscount> Discounts { get; set; }
        // To do . . .
        // Define the property for AmountPayable. Set the display label
        // to "Amount Payable (SGD)" and the display format to 2 decimal
        // places and comma at the thousand mark
        [Display(Name = "Amount Payable (SGD)")]
        [DisplayFormat(DataFormatString = "{0:#,##0.00}")]
        public double AmountPayable { get; set; }
    }

}

web_s10185214/web_s10185214/Controllers/RentalController.cs
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Http;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using web_s10185214.Models;

namespace web_s10185214.Controllers
{
    public class RentalController : Controller
    {
        // List that stores the options for days (duration) of loan
        private List<int> numLoanDays = new List<int> { 2, 5, 10, 20 };
        // List that stores the corresponding rental rate for each options
        private List<double> rentalRates = new List<double>{ 1.0, 1.50, 2.50, 5.00 };
        // A list for populating drop-down list
        private List<SelectListItem> numBooks = new List<SelectListItem>();
        // A list for populating checkbox list
        private List<RentalDiscount> discountList = new List<RentalDiscount>();

        // Constructor for the RentalController
        public RentalController()
        {
            //Populate the selection list for drop-down list
            for (int i = 1; i <= 10; i++)
            {
                numBooks.Add(
                new SelectListItem
                {
                    Value = i.ToString(),
                    Text = i.ToString(),
                });
            }
            //Populate the selection list for checkboxes list
            discountList.Add(
            new RentalDiscount
            {
                Description = "Student Membership (20%)",
                DiscountPercent = 20,
                Selected = false
            });
            discountList.Add(
            new RentalDiscount
            {
                Description = "Birthday Discount (10%)",
                DiscountPercent = 10,
                Selected = false
            });
        }
        public ActionResult Calculate()
        {
            //stop accessing the action if not logged in
            //or account not in the "staff" role
            //basically returns to home page if cannot login with correct credentials.
            if((HttpContext.Session.GetString("Role")==null) ||
                (HttpContext.Session.GetString("Role") != "Staff"))
            {
                return RedirectToAction("Index", "Home");
            }
            //Prepare the ViewData to be used in Calculate.cshtml view
            ViewData["ShowResult"] = false;
            ViewData["NumBooks"] = numBooks;
            ViewData["NumDays"] = numLoanDays;

            Rental rental = new Rental
            {
                LoanDate = DateTime.Today,
                // Set the default number of books loaned
                NumBooks = Convert.ToInt32(numBooks[0].Value),
                // Set the default number of days loaned
                NumDays = numLoanDays[0],
                // Display a list of discount
                Discounts = discountList
            };
            return View(rental);
        }
        public bool CheckDOB(Rental rental)
        {
            if(rental.DOB.Month == rental.LoanDate.Month)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        [HttpPost]
        public ActionResult Calculate(Rental rental)
        {
            //Prepare the ViewData to be used in Calculate.cshtml view
            ViewData["ShowResult"] = true;
            ViewData["NumBooks"] = numBooks;
            ViewData["NumDays"] = numLoanDays;
            // rental object contains user input in the Calculate.cshtml view
            // Compute Loan Due Date
            rental.DueDate = rental.LoanDate.AddDays(rental.NumDays);

            // Get rental rate based on number of day loan selection
            int selectedIndex = numLoanDays.IndexOf(rental.NumDays);
            rental.RentalRate = rentalRates[selectedIndex];
            // Calculate rental fee
            rental.RentalFee = rental.NumBooks *
            rental.NumDays * rental.RentalRate;
            // Calculate the discount percentage based on rental fee
            rental.DiscountPercent = 0.0;
            foreach (RentalDiscount discountItem in rental.Discounts)
            {
                if (discountItem.Selected) 
                { 
                    rental.DiscountPercent += discountItem.DiscountPercent; 
                }
            }
            if (CheckDOB(rental) == true)
            {
                rental.DiscountPercent += 10;
            }
            // Calculate the amount payable
            rental.AmountPayable = rental.RentalFee *
            (100 - rental.DiscountPercent) / 100;
            // Route to Calculate.cshtml view to display result
            // contained in the rental object
            return View(rental);
        }
    }
    //test test   
}

web_s10185214/web_s10185214/Views/Rental/Calculate.cshtml
@model web_s10185214.Models.Rental

@{
    ViewData["Title"] = "Rental Calculator";
}
<h4 class="PageTitle">Rental Calculator</h4>
<hr />
<form asp-controller="Rental" asp-action="Calculate" method="post">
    <fieldset class="FormContent">
        <legend>Input Data:</legend>
        <div class="form-group row">
            <label asp-for="LoanDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="LoanDate" readonly
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DOB"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9">
                <input asp-for="DOB" 
                       class="form-control-plaintext" />
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NumBooks"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 col-md-4">
                <select asp-for="NumBooks"
                        asp-items="@ViewData["NumBooks"] as List<SelectListItem>"
                        class="form-control"></select>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="NumDays"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 ">
                <div class="form-group form-check-inline">
                    @foreach (var item in ViewData["NumDays"]
                  as List<int>)
                    {
                        <label class="col-form-label">
                            <input asp-for="NumDays" type="radio"
                                   value="@item" class="form-check-input" />
                            <span style="font-weight:normal; padding-right:20px">@item</span>
                        </label>
                    }
                </div>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="Discounts"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 ">
                <div class="form-group form-check-inline">
                    @for (int i = 0; i < Model.Discounts.Count; i++)
                    {
                        if (Model.Discounts[i].Description == "Birthday Discount (10%)")
                        {
                            <label asp-for="Discounts[i].Selected"
                                   class="col-form-label"
                                   style="font-weight:normal; padding-right:20px">
                                @Model.Discounts[i].Description
                            </label>
                        }
                        else
                        {
                            <input asp-for="Discounts[i].Selected"
                                   type="checkbox" class="form-check-input" />
                            <label asp-for="Discounts[i].Selected"
                                   class="col-form-label"
                                   style="font-weight:normal; padding-right:20px">
                                @Model.Discounts[i].Description
                            </label>
                        }
                        <!-- Hidden fields to get value at server-side and states of checkbox list -->
                        <input type="hidden"
                               asp-for="Discounts[i].DiscountPercent" />
                        <input type="hidden"
                               asp-for="Discounts[i].Description" />
                    }
                </div>
            </div>
        </div>
        <div class="form-group row">
            <div class="col-sm-9 offset-sm-3">
                <input type="submit" value="Compute"
                       class="btn btn-primary" />
            </div>
        </div>
    </fieldset>
</form>
@if (Convert.ToBoolean(ViewData["ShowResult"]))
{
    <fieldset class="FormContent">
        <legend>Result:</legend>
        <div class="form-group row">
            <label asp-for="DueDate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("DueDate")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="RentalRate"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("RentalRate")
                <span style="padding:4px; font-style:italic;">
                    (per book per day)
                </span>
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="RentalFee"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("RentalFee")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="DiscountPercent"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("DiscountPercent")
            </div>
        </div>
        <div class="form-group row">
            <label asp-for="AmountPayable"
                   class="col-sm-3 col-form-label"></label>
            <div class="col-sm-9 form-control-plaintext">
                @Html.Display("AmountPayable")
            </div>
        </div>
    </fieldset>
}